"""Add listing_segment to IPO

Revision ID: 3760eae90459
Revises: 238a758092fe
Create Date: 2026-09-04 23:58:17.299103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3760eae90459'
down_revision: Union[str, None] = '238a758092fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipos', sa.Column('listing_segment', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_ipos_listing_segment'), 'ipos', ['listing_segment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipos_listing_segment'), table_name='ipos')
    op.drop_column('ipos', 'listing_segment')
    # ### end Alembic commands ###
