"""Phase 1B enrichment fields

Revision ID: 62985079b762
Revises: cb6bee80aa04
Create Date: 2026-09-02 00:54:14.099358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62985079b762'
down_revision: Union[str, None] = 'cb6bee80aa04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipos', sa.Column('open_date', sa.Date(), nullable=True))
    op.add_column('ipos', sa.Column('close_date', sa.Date(), nullable=True))
    op.add_column('ipos', sa.Column('listing_date', sa.Date(), nullable=True))
    op.add_column('ipos', sa.Column('fresh_issue', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('ipos', sa.Column('ofs', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('ipos', sa.Column('lot_size', sa.Integer(), nullable=True))
    op.add_column('ipos', sa.Column('min_investment', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('ipos', sa.Column('face_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('ipos', sa.Column('shares_offered', sa.Integer(), nullable=True))
    op.add_column('ipos', sa.Column('data_source', sa.String(length=100), nullable=True))
    op.add_column('ipos', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('ipos', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ipos', 'last_synced_at')
    op.drop_column('ipos', 'source_url')
    op.drop_column('ipos', 'data_source')
    op.drop_column('ipos', 'shares_offered')
    op.drop_column('ipos', 'face_value')
    op.drop_column('ipos', 'min_investment')
    op.drop_column('ipos', 'lot_size')
    op.drop_column('ipos', 'ofs')
    op.drop_column('ipos', 'fresh_issue')
    op.drop_column('ipos', 'listing_date')
    op.drop_column('ipos', 'close_date')
    op.drop_column('ipos', 'open_date')
    # ### end Alembic commands ###
