"""Phase 3A valuation context

Revision ID: 88bdd6b2b31e
Revises: d0ad286081f6
Create Date: 2026-09-03 17:45:14.364783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88bdd6b2b31e'
down_revision: Union[str, None] = 'd0ad286081f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipos', sa.Column('pre_issue_shares', sa.BigInteger(), nullable=True))
    op.add_column('ipos', sa.Column('post_issue_shares', sa.BigInteger(), nullable=True))
    op.add_column('ipos', sa.Column('fresh_issue_shares', sa.BigInteger(), nullable=True))
    op.add_column('ipos', sa.Column('ofs_shares', sa.BigInteger(), nullable=True))
    with op.batch_alter_table('ipos') as batch_op:
        batch_op.alter_column('shares_offered',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=True)
    op.add_column('valuation_metrics', sa.Column('context', sa.String(length=30), server_default='CURRENT_MARKET', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valuation_metrics', 'context')
    with op.batch_alter_table('ipos') as batch_op:
        batch_op.alter_column('shares_offered',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)
    op.drop_column('ipos', 'ofs_shares')
    op.drop_column('ipos', 'fresh_issue_shares')
    op.drop_column('ipos', 'post_issue_shares')
    op.drop_column('ipos', 'pre_issue_shares')
    # ### end Alembic commands ###
