"""Phase 2A financial models

Revision ID: d0ad286081f6
Revises: 62985079b762
Create Date: 2026-09-03 13:24:23.868658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ad286081f6'
down_revision: Union[str, None] = '62985079b762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_metrics', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('financial_metrics', sa.Column('source_reference', sa.String(length=255), nullable=True))
    op.add_column('financial_metrics', sa.Column('derived_fields', sa.JSON(), nullable=False))
    op.alter_column('financial_metrics', 'revenue',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    op.alter_column('financial_metrics', 'ebitda',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    op.alter_column('financial_metrics', 'ebit',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    op.alter_column('financial_metrics', 'pat',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    op.alter_column('financial_metrics', 'eps',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('financial_metrics', 'total_debt',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    op.alter_column('financial_metrics', 'cash',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    op.alter_column('financial_metrics', 'equity',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    op.alter_column('financial_metrics', 'assets',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    op.add_column('financial_periods', sa.Column('interim_period', sa.String(length=20), nullable=True))
    op.alter_column('valuation_metrics', 'market_cap',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    op.alter_column('valuation_metrics', 'ev',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valuation_metrics', 'ev',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    op.alter_column('valuation_metrics', 'market_cap',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    op.drop_column('financial_periods', 'interim_period')
    op.alter_column('financial_metrics', 'assets',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    op.alter_column('financial_metrics', 'equity',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    op.alter_column('financial_metrics', 'cash',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    op.alter_column('financial_metrics', 'total_debt',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    op.alter_column('financial_metrics', 'eps',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('financial_metrics', 'pat',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    op.alter_column('financial_metrics', 'ebit',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    op.alter_column('financial_metrics', 'ebitda',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    op.alter_column('financial_metrics', 'revenue',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               nullable=False)
    op.drop_column('financial_metrics', 'derived_fields')
    op.drop_column('financial_metrics', 'source_reference')
    op.drop_column('financial_metrics', 'source_type')
    # ### end Alembic commands ###
