"""Add v4.0 scoring fields

Revision ID: f16da429c593
Revises: 88bdd6b2b31e
Create Date: 2026-09-04 00:07:44.805490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16da429c593'
down_revision: Union[str, None] = '88bdd6b2b31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipo_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('financial_quality_score', sa.Float(), nullable=True),
    sa.Column('growth_score', sa.Float(), nullable=True),
    sa.Column('valuation_score', sa.Float(), nullable=True),
    sa.Column('balance_sheet_score', sa.Float(), nullable=True),
    sa.Column('business_quality_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('methodology_version', sa.String(length=40), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('explanations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ipo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipo_scores')
    # ### end Alembic commands ###
